Vagrant.configure("2") do |config|
  

  #router: que está conectada a una red pública (br0) y
   #a una red privada (muy aislada) red_intra. La máquina router
    #debe salir por la red pública.
   #Esta máquina no va a utilizar eth0 para acceder al exterior.

  
# Máquina 'router'
config.vm.define "router" do |router|
  router.vm.box = "debian/bookworm64"
  router.vm.hostname = "router"
  router.vm.synced_folder ".", "/vagrant", disabled: true
   
  # Puente a la red pública
  router.vm.network :public_network,
    dev: "br0",
    mode: "bridge",
    type: "bridge"
    
  # Red privada muy aislada 'red_intra'
  router.vm.network :private_network,
    libvirt__network_name: "red_intra",
    libvirt__dhcp_enabled: false,
    ip: "192.168.33.10",
    libvirt__forward_mode: "none"
end

# Máquina 'web'
config.vm.define "web" do |web|
  web.vm.box = "debian/bookworm64"
  web.vm.hostname = "web"
  web.vm.synced_folder ".", "/vagrant", disabled: true
  
  # Red privada muy aislada 'red_intra', conexión con 'router'
  web.vm.network :private_network,
    libvirt__network_name: "red_intra",
    libvirt__dhcp_enabled: false,
    ip: "192.168.33.11",
    libvirt__forward_mode: "none"
    
  # Otra red privada muy aislada 'red_datos', conexión con 'bd'
  web.vm.network :private_network,
    libvirt__network_name: "red_datos",
    libvirt__dhcp_enabled: false,
    ip: "192.168.34.11",
    libvirt__forward_mode: "none"
end

# Máquina 'bd'
config.vm.define "bd" do |bd|
  bd.vm.box = "debian/bookworm64"
  bd.vm.hostname = "bd"
  bd.vm.synced_folder ".", "/vagrant", disabled: true
  
  # Red privada muy aislada 'red_intra', conexión con 'router'
  bd.vm.network :private_network,
    libvirt__network_name: "red_intra",
    libvirt__dhcp_enabled: false,
    ip: "192.168.33.12",
    libvirt__forward_mode: "none"
    
  # Otra red privada muy aislada 'red_datos', conexión con 'web'
  bd.vm.network :private_network,
    libvirt__network_name: "red_datos",
    libvirt__dhcp_enabled: false,
    ip: "192.168.34.12",
    libvirt__forward_mode: "none"
end
end 

